TYPE=VIEW
query=select `huiyoufu`.`t_store_activities_info`.`fticiket_code` AS `fticiket_code`,`huiyoufu`.`t_store_activities_info`.`fticiket_name` AS `fticiket_name`,`huiyoufu`.`t_store_activities_info`.`fticiket_validity_start` AS `fticiket_validity_start`,`huiyoufu`.`t_store_activities_info`.`fticiket_validity_stop` AS `fticiket_validity_stop`,`huiyoufu`.`t_store_activities_info`.`fticiket_picture` AS `fticiket_picture`,`huiyoufu`.`t_store_activities_info`.`fwinning_rate` AS `fwinning_rate`,`huiyoufu`.`t_store_activities`.`fstart_time` AS `fstart_time`,`huiyoufu`.`t_store_activities`.`fstop_time` AS `fstop_time`,`huiyoufu`.`t_store_activities`.`fpartake_frequency_day` AS `fpartake_frequency_day`,`huiyoufu`.`t_store_activities`.`fpartake_frequency_week` AS `fpartake_frequency_week`,`huiyoufu`.`t_store_activities`.`fpartake_frequency_month` AS `fpartake_frequency_month`,`huiyoufu`.`t_store_activities`.`fpublic_activies_state` AS `fpublic_activies_state`,`huiyoufu`.`t_store_activities`.`fstore_activies_state` AS `fstore_activies_state`,`huiyoufu`.`t_store_activities`.`fstore_code` AS `fstore_code`,`huiyoufu`.`t_store_activities`.`factivites_id` AS `factivites_id` from (`huiyoufu`.`t_store_activities` join `huiyoufu`.`t_store_activities_info` on((`huiyoufu`.`t_store_activities`.`factivites_id` = `huiyoufu`.`t_store_activities_info`.`ft_store_activities_factivies_id`))) where ((`huiyoufu`.`t_store_activities`.`fpublic_activies_state` = 1) and (`huiyoufu`.`t_store_activities`.`fstore_activies_state` = 1))
md5=9aa024a07d3d4f0357bc7723ae1ca56a
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2019-01-21 12:37:53
create-version=1
source=SELECT\n`t_store_activities_info`.`fticiket_code`,\n`t_store_activities_info`.`fticiket_name`,\n`t_store_activities_info`.`fticiket_validity_start`,\n`t_store_activities_info`.`fticiket_validity_stop`,\n`t_store_activities_info`.`fticiket_picture`,\n`t_store_activities_info`.`fwinning_rate`,\n`t_store_activities`.`fstart_time`,\n`t_store_activities`.`fstop_time`,\n`t_store_activities`.`fpartake_frequency_day`,\n`t_store_activities`.`fpartake_frequency_week`,\n`t_store_activities`.`fpartake_frequency_month`,\n`t_store_activities`.`fpublic_activies_state`,\n`t_store_activities`.`fstore_activies_state`,\n`t_store_activities`.`fstore_code`,\n`t_store_activities`.`factivites_id`\nFROM\n`t_store_activities`\nINNER JOIN `t_store_activities_info` ON `t_store_activities`.`factivites_id` = `t_store_activities_info`.`ft_store_activities_factivies_id`\nWHERE\n`t_store_activities`.`fpublic_activies_state` = 1 AND\n`t_store_activities`.`fstore_activies_state` = 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `huiyoufu`.`t_store_activities_info`.`fticiket_code` AS `fticiket_code`,`huiyoufu`.`t_store_activities_info`.`fticiket_name` AS `fticiket_name`,`huiyoufu`.`t_store_activities_info`.`fticiket_validity_start` AS `fticiket_validity_start`,`huiyoufu`.`t_store_activities_info`.`fticiket_validity_stop` AS `fticiket_validity_stop`,`huiyoufu`.`t_store_activities_info`.`fticiket_picture` AS `fticiket_picture`,`huiyoufu`.`t_store_activities_info`.`fwinning_rate` AS `fwinning_rate`,`huiyoufu`.`t_store_activities`.`fstart_time` AS `fstart_time`,`huiyoufu`.`t_store_activities`.`fstop_time` AS `fstop_time`,`huiyoufu`.`t_store_activities`.`fpartake_frequency_day` AS `fpartake_frequency_day`,`huiyoufu`.`t_store_activities`.`fpartake_frequency_week` AS `fpartake_frequency_week`,`huiyoufu`.`t_store_activities`.`fpartake_frequency_month` AS `fpartake_frequency_month`,`huiyoufu`.`t_store_activities`.`fpublic_activies_state` AS `fpublic_activies_state`,`huiyoufu`.`t_store_activities`.`fstore_activies_state` AS `fstore_activies_state`,`huiyoufu`.`t_store_activities`.`fstore_code` AS `fstore_code`,`huiyoufu`.`t_store_activities`.`factivites_id` AS `factivites_id` from (`huiyoufu`.`t_store_activities` join `huiyoufu`.`t_store_activities_info` on((`huiyoufu`.`t_store_activities`.`factivites_id` = `huiyoufu`.`t_store_activities_info`.`ft_store_activities_factivies_id`))) where ((`huiyoufu`.`t_store_activities`.`fpublic_activies_state` = 1) and (`huiyoufu`.`t_store_activities`.`fstore_activies_state` = 1))
